Add script termination option to 'Lua Scripts' floater
secondlife/viewer pull request #1152
Opened 2024-04-08 14:05 UTC by maxim-productengine

Add the way to terminate selected script in 'Lua Scripts' floater: call `lluau::error` when it's needed (but if the script is blocked in `getNext()`, close the queue first).

2024-04-10 20:41 UTC, nat-goodspeed commented
Maxim, thanks, I'm looking, but it will probably be tomorrow before I can respond.

2024-04-12 14:18 UTC, nat-goodspeed requested changes
I know you're still working on this, so maybe my comments have become moot. But there are a couple things in this PR as it now stands that I'd like to see changed.

2024-04-12 14:18 UTC, nat-goodspeed commented on indra/newview/llluamanager.cpp
> +                    return;
A comment explaining the meaning of the `gc` parameter would be helpful here.

2024-04-12 14:18 UTC, nat-goodspeed commented on indra/newview/llluamanager.cpp
> +                    sTerminationList.erase(coro);
Maybe capture the iterator returned by `find()` and `erase()` that?

Oh! I don't think this `erase()` will actually affect `sTerminationList`! `getTerminationList()` returns `std::set<std::string>` by value, so in this function `scripts` is a _copy_ of `sTerminationList`!

Maybe `runScriptFile()` could directly reference `sTerminationList`?

2024-04-12 16:39 UTC, maxim-productengine commented on indra/newview/llfloaterluascripts.cpp
> +            mCoroName = item->getValue().asString();
Yes, that what we usually use for the scroll list menu.
I got rid of mTargetFolderPath and mCoroName, and moved appropriate code to the callback part.

2024-04-12 16:46 UTC, maxim-productengine commented on indra/llcommon/llapp.cpp
> +        LLEventPumps::instance().obtain("LLLua").post(llsd::map("status", "close_all"));
To be honest I missed the ability to terminate coroutine once or twice in the past when working on maint bugs. So, I'm for it.

I made changes according to your comments. And I'm not planning any more changes for now for this PR. (there will be some changes related to script termination as you know, but I'll create separate pr)

2024-04-12 20:40 UTC, nat-goodspeed approved these changes
Thanks, Maxim!

2024-04-12 20:40 UTC, merged

2024-04-13 12:53 UTC, nat-goodspeed commented on indra/llcommon/llapp.cpp
> +        LLEventPumps::instance().obtain("LLLua").post(llsd::map("status", "close_all"));
I'm sorry to say I overlooked an important point. I can indeed introduce a flag for the next time a given coroutine wakes up and calls `LLCoros::checkStop()`, but I can't cause that coroutine to wake up and check it. An `LLEventStream` listener runs on the coroutine calling `post()`. An exception thrown by such a listener will propagate through the `post()` call.

The Boost.Fiber library we use does not provide a way to force an exception onto a suspended fiber -- although tantalizingly, the Boost.Context library on which it's based provides a mechanism that could support that. At present, the best we can do is to wait for the subject coroutine to call `checkStop()`.