Update to S3-published GHA build of slvoice.
secondlife/viewer pull request #1444
Opened 2024-05-09 16:32 UTC by nat-goodspeed

2024-05-09 20:35 UTC, vir-linden approved these changes

2024-05-09 21:36 UTC, bennettgoble requested changes
The indentation vacillations in autobuild.xml should be fixed with autobuild v3.9.4. https://github.com/secondlife/autobuild/releases/tag/v3.9.4

2024-05-10 14:19 UTC, bennettgoble commented
Approved, but the llcoros change is unrelated --could/should be in a separate PR.

2024-05-10 14:34 UTC, nat-goodspeed commented
I did that because the previous run failed with stack overflow.

2024-05-10 15:02 UTC, merged