Enable C++20 standard
secondlife/viewer pull request #2330
Opened 2024-08-18 11:54 UTC by Ansariel

The following issues had to be resolved in order to achieve C++20 compatibility:
* std::result_of has been deprecated since C++17 and was removed with C++20. Replaced with std::invoke_result and its respective helper std::invoke_result_t
* "requires" is a keyword as of C++20, so the method with the same name in Rule (llpredicate.h) has been renamed to "required" (also seems to be unused anyway)
* Implicit capture of &(*this) via value-capture-default ([=]) has been deprecated. Replaced affected cases with "[=, this]"
* Compiler gets very picky about (un)equal operations between T* and LLPointer<T>. Changed order of arguments so LLPointer<T> is on the left-hand side and T* on the right-hand side to use overloaded operators from LLPointer instead of having to call LLPointer<T>::get()
* u8 character literal has type char8_t instead of char since C++20 - use reinterpret_cast<const char*> to cast to compatible type in LLPanelEmojiComplete::updateConstraints()
* std::shared_ptr::unique() has been removed in C++20 - replaced check in test_httpoperation.hpp with std::shared_ptr::use_count() since the test was basically wrong because of a copy-paste-error anyway

2024-08-19 05:33 UTC, marchcat approved these changes
Thank you very much!

2024-08-19 07:00 UTC, marchcat requested changes
```
/Users/runner/work/viewer/viewer/indra/llwindow/llwindowmacosx.cpp:1043:21: error: comparison of different enumeration types ('CGError' and '(unnamed enum at /Applications/Xcode_14.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/MacTypes.h:382:1)') is deprecated [-Werror,-Wdeprecated-anon-enum-enum-conversion]
        &blueGamma) == noErr)
        ~~~~~~~~~~~ ^  ~~~~~
/Users/runner/work/viewer/viewer/indra/llwindow/llwindowmacosx.cpp:1094:21: error: comparison of different enumeration types ('CGError' and '(unnamed enum at /Applications/Xcode_14.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/MacTypes.h:382:1)') is deprecated [-Werror,-Wdeprecated-anon-enum-enum-conversion]
        &blueGamma) != noErr)
        ~~~~~~~~~~~ ^  ~~~~~
/Users/runner/work/viewer/viewer/indra/llwindow/llwindowmacosx.cpp:1109:16: error: comparison of different enumeration types ('CGError' and '(unnamed enum at /Applications/Xcode_14.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/MacTypes.h:382:1)') is deprecated [-Werror,-Wdeprecated-anon-enum-enum-conversion]
        gamma) != noErr)
        ~~~~~~ ^  ~~~~~
/Users/runner/work/viewer/viewer/indra/llwindow/llwindowmacosx.cpp:1161:47: error: comparison of different enumeration types ('CGError' and '(unnamed enum at /Applications/Xcode_14.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/MacTypes.h:382:1)') is deprecated [-Werror,-Wdeprecated-anon-enum-enum-conversion]
    if(CGWarpMouseCursorPosition(newPosition) == noErr)
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~
4 errors generated.
```

For some reason, it gives me another set of errors on my mac (Sonoma 14.6.1, Xcode 15.4). Will probably did deeper.

@Ansariel can you read the build logs in the bottom section of this PR?

2024-08-19 07:57 UTC, Ansariel commented
> For some reason, it gives me another set of errors on my mac (Sonoma 14.6.1, Xcode 15.4). Will probably dig deeper.
> 
> @Ansariel can you read the build logs in the bottom section of this PR?

I don't have a Mac, so I had to fix it "blind" using the Apple documentation - hopefully.

2024-08-19 07:59 UTC, marchcat commented
> I don't have a Mac, so I had to fix it "blind" using the Apple documentation - hopefully.

I'm on it. There are more build errors, but I have some progress. Will update once ready.

2024-08-19 08:08 UTC, marchcat commented
Xcode complains about `Lambda capture 'this' is not used`, I'll comment them out for now.

2024-08-19 08:12 UTC, Ansariel commented
> Xcode complains about `Lambda capture 'this' is not used`, I'll comment them out for now.

Ah! That might be the case if the lamba function doesn't actually use anything from the captured instance. I'll just replaced every case where this was captured implicitly to include it explicitly. Guess we now find out where it is not needed. :D

2024-08-19 09:25 UTC, marchcat commented
I'm not sure if I did it right, but at least the viewer builds on my mac now. Let's test the builds here as well: #2337

2024-08-19 09:34 UTC, marchcat commented
And now it throws
```
/Users/runner/work/viewer/viewer/indra/llui/lllayoutstack.cpp:837:39: error: no member named 'views' in namespace 'std'
    for (auto panelp : mPanels | std::views::reverse)
                                 ~~~~~^
/Users/runner/work/viewer/viewer/indra/llui/lllayoutstack.cpp:995:47: error: no member named 'views' in namespace 'std'
    for (auto visible_panelp : mPanels | std::views::reverse)
                                         ~~~~~^
2 errors generated.
```

so the GHA env. should be reconfigured to fully support C++20 as well.

2024-08-19 10:12 UTC, Ansariel commented
> And now it throws
> 
> ```
> /Users/runner/work/viewer/viewer/indra/llui/lllayoutstack.cpp:837:39: error: no member named 'views' in namespace 'std'
>     for (auto panelp : mPanels | std::views::reverse)
>                                  ~~~~~^
> /Users/runner/work/viewer/viewer/indra/llui/lllayoutstack.cpp:995:47: error: no member named 'views' in namespace 'std'
>     for (auto visible_panelp : mPanels | std::views::reverse)
>                                          ~~~~~^
> 2 errors generated.
> ```
> 
> so the GHA env. should be reconfigured to fully support C++20 as well.

Clang again... 😠 

Can you try if it works by changing the 2 loops to
```
    std::ranges::reverse_view panels_reversed{ mPanels };
    for (auto panelp : panels_reversed)
```
and
```
    std::ranges::reverse_view panels_reversed{ mPanels };
    for (auto visible_panelp : panels_reversed)
```
respectively?

2024-08-19 16:57 UTC, marchcat commented
> Clang again... 😠
> 
> @marchcat Can you try if it works by changing the 2 loops to
> 
> ```
>     std::ranges::reverse_view panels_reversed{ mPanels };
>     for (auto panelp : panels_reversed)
> ```
> 
> and
> 
> ```
>     std::ranges::reverse_view panels_reversed{ mPanels };
>     for (auto visible_panelp : panels_reversed)
> ```
> 
> respectively?

That didn't work either, so I've replaced them with manual reverse iterations for now.

2024-08-19 17:38 UTC, Ansariel commented
> That didn't work either, so I've replaced them with manual reverse iterations for now.

Kinda annoying. Really might need a newer SDK version then. 😞 

Could have just reverted the one commit and go bach to boost's reverse for-each for the time being though.

2024-08-19 19:17 UTC, marchcat commented
> Kinda annoying. Really might need a newer SDK version then. 😞

Most likely. I made some progress (in [7590edc](https://github.com/secondlife/viewer/pull/2337/commits/7590edcdc47170f3dc3e001cc0beb3a6ab306eb3)) but now encountered this:
```
While building module 'Cocoa' imported from /Users/runner/work/viewer/viewer/indra/llwindow/llappdelegate-objc.h:27:
While building module 'AppKit' imported from /Applications/Xcode_14.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:13:
While building module 'CoreData' imported from /Applications/Xcode_14.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSKeyValueBinding.h:12:
In file included from <module-includes>:2:
In file included from /Applications/Xcode_14.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/System/Library/Frameworks/CoreData.framework/Headers/CoreData.h:64:
/Applications/Xcode_14.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/System/Library/Frameworks/CoreData.framework/Headers/NSPersistentCloudKitContainerEvent.h:22:1: error: unknown type name 'COREDATA_EXTERN'
COREDATA_EXTERN NSNotificationName const NSPersistentCloudKitContainerEventChangedNotification API_AVAILABLE(macosx(11.0),ios(14.0),tvos(14.0),watchos(7.0)) NS_SWIFT_NAME(NSPersistentCloudKitContainer.eventChangedNotification);
^
/Applications/Xcode_14.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/System/Library/Frameworks/CoreData.framework/Headers/NSPersistentCloudKitContainerEvent.h:22:35: error: expected ';' after top level declarator
COREDATA_EXTERN NSNotificationName const NSPersistentCloudKitContainerEventChangedNotification API_AVAILABLE(macosx(11.0),ios(14.0),tvos(14.0),watchos(7.0)) NS_SWIFT_NAME(NSPersistentCloudKitContainer.eventChangedNotification);
                                  ^
/Applications/Xcode_14.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/System/Library/Frameworks/CoreData.framework/Headers/NSPersistentCloudKitContainerEvent.h:22:42: error: unknown type name 'NSPersistentCloudKitContainerEventChangedNotification'
COREDATA_EXTERN NSNotificationName const NSPersistentCloudKitContainerEventChangedNotification API_AVAILABLE(macosx(11.0),ios(14.0),tvos(14.0),watchos(7.0)) NS_SWIFT_NAME(NSPersistentCloudKitContainer.eventChangedNotification);
                                         ^
/Applications/Xcode_14.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/System/Library/Frameworks/CoreData.framework/Headers/NSPersistentCloudKitContainerEvent.h:23:1: error: unknown type name 'COREDATA_EXTERN'
COREDATA_EXTERN NSString * const NSPersistentCloudKitContainerEventUserInfoKey API_AVAILABLE(macosx(11.0),ios(14.0),tvos(14.0),watchos(7.0)) NS_SWIFT_NAME(NSPersistentCloudKitContainer.eventNotificationUserInfoKey);
^
/Applications/Xcode_14.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/System/Library/Frameworks/CoreData.framework/Headers/NSPersistentCloudKitContainerEvent.h:23:25: error: expected ';' after top level declarator
COREDATA_EXTERN NSString * const NSPersistentCloudKitContainerEventUserInfoKey API_AVAILABLE(macosx(11.0),ios(14.0),tvos(14.0),watchos(7.0)) NS_SWIFT_NAME(NSPersistentCloudKitContainer.eventNotificationUserInfoKey);
                        ^
While building module 'Cocoa' imported from /Users/runner/work/viewer/viewer/indra/llwindow/llappdelegate-objc.h:27:
While building module 'AppKit' imported from /Applications/Xcode_14.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:13:
While building module 'CoreData' imported from /Applications/Xcode_14.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSKeyValueBinding.h:12:
In file included from <module-includes>:2:
In file included from /Applications/Xcode_14.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/System/Library/Frameworks/CoreData.framework/Headers/CoreData.h:67:
/Applications/Xcode_14.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/System/Library/Frameworks/CoreData.framework/Headers/NSCoreDataCoreSpotlightDelegate.h:34:1: error: unknown type name 'COREDATA_EXTERN'
COREDATA_EXTERN NSNotificationName const NSCoreDataCoreSpotlightDelegateIndexDidUpdateNotification API_AVAILABLE(macosx(11.0),ios(14.0),tvos(NA),watchos(NA));
^
/Applications/Xcode_14.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/System/Library/Frameworks/CoreData.framework/Headers/NSCoreDataCoreSpotlightDelegate.h:34:35: error: expected ';' after top level declarator
COREDATA_EXTERN NSNotificationName const NSCoreDataCoreSpotlightDelegateIndexDidUpdateNotification API_AVAILABLE(macosx(11.0),ios(14.0),tvos(NA),watchos(NA));
                                  ^
/Applications/Xcode_14.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/System/Library/Frameworks/CoreData.framework/Headers/NSCoreDataCoreSpotlightDelegate.h:34:42: error: unknown type name 'NSCoreDataCoreSpotlightDelegateIndexDidUpdateNotification'
COREDATA_EXTERN NSNotificationName const NSCoreDataCoreSpotlightDelegateIndexDidUpdateNotification API_AVAILABLE(macosx(11.0),ios(14.0),tvos(NA),watchos(NA));
                                         ^
/Applications/Xcode_14.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/System/Library/Frameworks/CoreData.framework/Headers/NSCoreDataCoreSpotlightDelegate.h:65:46: error: expected a type
                                coordinator:(NSPersistentStoreCoordinator *)psc NS_DESIGNATED_INITIALIZER API_AVAILABLE(macosx(10.15),ios(13.0),tvos(NA),watchos(NA));
                                             ^
9 errors generated.
While building module 'Cocoa' imported from /Users/runner/work/viewer/viewer/indra/llwindow/llappdelegate-objc.h:27:
While building module 'AppKit' imported from /Applications/Xcode_14.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:13:
In file included from <module-includes>:2:
In file included from /Applications/Xcode_14.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/System/Library/Frameworks/AppKit.framework/Headers/AppKit.h:16:
In file included from /Applications/Xcode_14.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSAlert.h:11:
In file included from /Applications/Xcode_14.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSApplication.h:14:
In file included from /Applications/Xcode_14.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSUserActivity.h:11:
In file included from /Applications/Xcode_14.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSDocument.h:16:
/Applications/Xcode_14.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSKeyValueBinding.h:12:9: fatal error: could not build module 'CoreData'
#import <CoreData/NSManagedObjectContext.h>
 ~~~~~~~^
While building module 'Cocoa' imported from /Users/runner/work/viewer/viewer/indra/llwindow/llappdelegate-objc.h:27:
While building module 'AppKit' imported from /Applications/Xcode_14.0.1.app/Contents/Developer/Platforms/MacOSX.platform/De [...]

2024-08-19 19:25 UTC, Ansariel commented
So apparently ranges needs at least XCode 14.3. Full support for C++20 needs apparently XCode 16. See https://developer.apple.com/xcode/cpp/#c++20 for the full list of disaster.

2024-08-19 21:07 UTC, marchcat commented
> Looks like you need to use a [macos-13 runner](https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md) to get support for that. Can this easily be tested in a PR-branch?

Yes, let's try this.

2024-08-19 21:21 UTC, nat-goodspeed reviewed
Thank you for plowing through the necessary fixes! I've been hoping to get to this for a couple years now.

I'm distressed to learn (thanks for the link) that we can't use all of C++20 on Mac until Xcode 16. I just checked the App Store, and evidently the Xcode 15.4 that I already have is still the latest official download. And of course Apple is famous for not revealing ship dates.

Even if we were willing to work with the subset of C++20 supported by Xcode 15.4, (for instance) this version apparently lacks `CGError::success`. Nor do the places you changed work with the original `noErr`. To try to get a local build, I used `CGError(0)`.

Moreover, Xcode clang turns up errors not surfaced on Windows. It doesn't like `(LLDrawPoolAlpha::VERTEX_DATA_MASK | LLVertexBuffer::MAP_TEXTURE_INDEX)`, a bitwise OR between different enum types. On Mac, `wchar_t` is actually 32 bits, so `llwchar` is `wchar_t` instead of `U32` as on Windows -- which surfaces conversion problems trying to write such strings to a `char`-based stream. And so on. I haven't yet gotten through a successful build; I guess marchcat has gotten farther (and hit more errors).

We could accept your changes, not to lose the work you've done for this, but I'm upset to admit that I don't believe we can turn on C++20 yet.

2024-08-19 21:25 UTC, Ansariel commented on indra/newview/llpanelemojicomplete.cpp
> +    mEmojiWidth = (U16)(mIconFont->getWidthF32(reinterpret_cast<const char*>(u8"\U0001F431")) + mPadding * 2);
Because that's what the kitty @KittyBarnett came up with 😸

2024-08-19 21:43 UTC, marchcat commented
And now it fails the test..
```
[llgltfmaterial, 12] fail: 'LLGLTFMaterial: Hash: Perturbing mTrackingIdToLocalTexture to new value does NOT change the hash: expected '1bf13c8f-3a85-ec32-b4bd-423a603c2b7d' actual 'e110e8f5-1085-2189-afc7-52a54d50b333''
```
But I can resolve that using my mac again. On the GitHub side, the `macos-13-xl` runner with Xcode 15.0 seems to work fine with this code otherwise.

@Ansariel, you can probably just merge my branch `marchcat/pr2330-mac-buildfix` directly into your `Ansariel:develop_c++20` since I'm unable to retarget my PR there.

2024-08-19 21:46 UTC, Ansariel commented
> Even if we were willing to work with the subset of C++20 supported by Xcode 15.4, (for instance) this version apparently lacks `CGError::success`. Nor do the places you changed work with the original `noErr`. To try to get a local build, I used `CGError(0)`.

I think that's why `kCGErrorSuccess` exists - no idea where it came from, but I also found that in some of the results when searching for it.

> Moreover, Xcode clang turns up errors not surfaced on Windows. It doesn't like `(LLDrawPoolAlpha::VERTEX_DATA_MASK | LLVertexBuffer::MAP_TEXTURE_INDEX)`, a bitwise OR between different enum types. On Mac, `wchar_t` is actually 32 bits, so `llwchar` is `wchar_t` instead of `U32` as on Windows -- which surfaces conversion problems trying to write such strings to a `char`-based stream. And so on. I haven't yet gotten through a successful build; I guess marchcat has gotten farther (and hit more errors).

To be fair, a bitwise operation between two different enum types feels sketchy and wouldn't even work at all if using an enum class type. 😉 

The wide char issue itself isn't new. Is there a particular reason you think switching to C++20 might create a new or unforeseen issue in this regard?

> We could accept your changes, not to lose the work you've done for this, but I'm upset to admit that I don't believe we can turn on C++20 yet.

The unfortunate problem in that case would be, that only half of the changes could be cherry picked. That is
* std::result_of replacement
* fixes for the comparison of `T*` and `LLPointer<T>`
* the std::shared_ptr issue
* the `requires` issue (in whatever way)

The value-capture-default change is of course something that can't be picked simply because it is not supported in C++17 yet. The alternative would be to switch to explicit captures instead.

2024-08-19 21:48 UTC, Ansariel commented on indra/llcommon/llpredicate.h
> +        bool required(const Value<ENUM> value) const
I can restore the original change again.

2024-08-19 22:00 UTC, Ansariel commented
> But I can resolve that using my mac again. On the GitHub side, the `macos-13-xl` runner with Xcode 15.0 seems to work fine with this code otherwise.
> 
> @Ansariel, you can probably just merge my branch `marchcat/pr2330-mac-buildfix` directly into your `Ansariel:develop_c++20` since I'm unable to retarget my PR there.

Merged it into my branch. It would be interesting to see if the ranges views now. I assume they do according to the XCode feature list (supported with 14.3)

2024-08-19 22:03 UTC, marchcat commented
> It would be interesting to see if the ranges views now. I assume they do according to the XCode feature list (supported with 14.3)

Right, we can bring that part back since it works on windows too.

2024-08-20 00:14 UTC, Ansariel commented on indra/llprimitive/llprimitive.cpp
> +        if (mVolumep == volumep)
Added the suggested overloaded operators.

2024-08-20 00:18 UTC, Ansariel commented
> And now it fails the test..
> 
> ```
> [llgltfmaterial, 12] fail: 'LLGLTFMaterial: Hash: Perturbing mTrackingIdToLocalTexture to new value does NOT change the hash: expected '1bf13c8f-3a85-ec32-b4bd-423a603c2b7d' actual 'e110e8f5-1085-2189-afc7-52a54d50b333''
> ```
> 
> But I can resolve that using my mac again. On the GitHub side, the `macos-13-xl` runner with Xcode 15.0 seems to work fine with this code otherwise.

This is kinda weird as the test works fine on Windows. Are newer XCode versions maybe messing with the alignment of class members?

2024-08-20 10:11 UTC, marchcat commented
> @marchcat can we try a build on the macos-14 runner with XCode 15.4 to see if that fixes the mysterious issue with the test before you start poking at the problem in the code?

Sure, I already have xcode 15.4 on my mac, so will check the tests there.

2024-08-20 20:20 UTC, marchcat commented
So I can confirm that the same test fails on xcode 15.4.
https://github.com/secondlife/viewer/blob/a0da63db57b4799cf67df4618afe70760840a719/indra/llprimitive/tests/llgltfmaterial_test.cpp#L426 
Commenting out this line helps and the viewer builds successfully, but this is not the solution we're looking for.

2024-08-20 20:47 UTC, Ansariel commented
> So I can confirm that the same test fails on xcode 15.4.
> 
> https://github.com/secondlife/viewer/blob/642ff2078a57ed1da9c72653aac5890a175fcac3/indra/llprimitive/tests/llgltfmaterial_test.cpp#L426
> 
> Commenting out this line helps and viewer builds successfully, but this is not the solution we're looking for.

It seems to be messing with the class alignment somehow. Not sure if there is some info available on that and if it can be prevented somehow. Which also leads to the question if this hack of generating a hash is the best idea (it's also done for the old Blinn-Phong materials, but there is probably no test available for it).

2024-08-20 23:09 UTC, nat-goodspeed commented
Correct hashing of composite data consists of hashing individual fields and combining. [getHash()](https://github.com/secondlife/viewer/blob/642ff2078a57ed1da9c72653aac5890a175fcac3/indra/llprimitive/llgltfmaterial.cpp#L863-L877) is fragile in that it _is_ sensitive to variations in struct packing. The solution is to change that implementation.

2024-08-28 16:02 UTC, KittyBarnett commented on indra/newview/llpanelemojicomplete.cpp
> +    mEmojiWidth = (U16)(mIconFont->getWidthF32(reinterpret_cast<const char*>(u8"\U0001F431")) + mPadding * 2);
Cats are a useful reference metric 😸.

2024-08-29 15:34 UTC, nat-goodspeed commented on indra/newview/llpanelemojicomplete.cpp
> +    mEmojiWidth = (U16)(mIconFont->getWidthF32(reinterpret_cast<const char*>(u8"\U0001F431")) + mPadding * 2);
I don't disagree! I just think a comment explaining that hex constant would improve it.

2024-10-24 16:39 UTC, nat-goodspeed commented
n.b. https://github.com/secondlife/viewer/blob/develop/indra/CMakeLists.txt#L32

2024-10-24 21:54 UTC, Ansariel commented
> n.b. https://github.com/secondlife/viewer/blob/develop/indra/CMakeLists.txt#L32

Nice! I creates #2944 with the changes from this PR that are not in the `develop` branch yet and closing this PR.

@vldevel Please create a PR against `develop` for what you think is wrong and needs to be fixed.

2024-10-24 21:54 UTC, closed without merging