Lua api for autopilot functions
secondlife/viewer pull request #2583
Opened 2024-09-17 09:55 UTC by maxim-productengine

Also made some tweaks and fixed detection of appropriate nearby object (we don't need attachments in all cases, but need extra check if we're looking for sit target).
When autopilot is terminated, success/fail status is posted to the event pump, which can be used by the script.
Changed LLChatListener to more general LLListener, which can be used for setting any pump listener, instead of just nearby chat.

2024-09-23 21:08 UTC, nat-goodspeed requested changes
I like most of this. The change I want to see is in the new generalized `LLListener`. Thanks!

2024-09-26 13:40 UTC, maxim-productengine commented on indra/newview/llagentlistener.cpp
> +        "[\"stop_distance\"]: target maximum distance from target [default: autopilot guess]\n"
Changed this description to 'maximum stop distance from target'.

2024-09-26 13:46 UTC, maxim-productengine commented on indra/newview/llagentlistener.cpp
> +        std::string target_info = event_data.has("leader_id") ? event_data["target_id"] : event_data["avatar_name"];
Thanks, it should be `event_data["leader_id"]`

2024-09-26 14:16 UTC, maxim-productengine commented on indra/newview/scripts/lua/require/LLAgent.lua
> +--                      [, target_rotation]    array of [x, y, z, w] quaternion values [default: no target]
Yes, exactly, `target_rotation ` specifies desired avatar facing direction, for example related to our map:
target_rotation={0,0,-0.71,0.71} -- facing South
target_rotation={0,0,0.71,0.71} -- facing North
target_rotation={0,0,0,1} -- facing East
target_rotation={0,1,0,0}-- facing West

Basically, we're rotating x_axis (1, 0, 0) vector to the desired rotation using this quaternion.

2024-09-26 14:22 UTC, closed without merging