#2112 Provide SL Grid Map coordinates for Official Viewer Users please
secondlife/viewer pull request #2829
Opened 2024-10-10 09:08 UTC by LLGuru

The grid coordinates of every region are being displayed just above the region name for each tile
![image](https://github.com/user-attachments/assets/092d6a63-8a5f-4994-8e2e-d9740cea1733)

2024-10-10 09:11 UTC, akleshchev commented
That seems like an odd choice of position to me. Name would be more relevant so I would have put it on top.

@kylelinden Are you fine with this?

2024-10-10 09:24 UTC, maxim-productengine commented
It looks ok, but in my opinion, this info should be optional. We can add a simple checkbox to World map for that, or at least hide it behind debug setting (because it seems somewhat niche information).

2024-10-10 09:41 UTC, aiaustin commented
Yes, more clutter on the maps is not needed for most people. If its needed it might be best behind a tick box with default being off.

2024-10-10 09:49 UTC, marchcat commented
+1 for a tick box.

2024-10-10 09:51 UTC, LLGuru commented
Comparing to the Firestorm viewer
![image](https://github.com/user-attachments/assets/0872ad3b-af13-49b1-abef-35245827d774)
![image](https://github.com/user-attachments/assets/720ece8b-d4b7-4e6d-ae99-2c76f8ef7a51)

2024-10-10 17:06 UTC, LLGuru commented
With a check box (AKA tick box):
![image](https://github.com/user-attachments/assets/6cdacdad-a331-4899-914e-987df88cc3d4)
![image](https://github.com/user-attachments/assets/c4ff4491-4075-49a2-b2f9-660cbaed75dd)

2024-10-10 17:16 UTC, marchcat reviewed
Is all the whitespace change in floater_world_map.xml necessary?

2024-10-10 17:31 UTC, Ansariel commented
> Is all the whitespace change in floater_world_map.xml necessary?

If you want to annoy TPVs: yes!

2024-10-11 07:43 UTC, LLGuru commented
> Is all the whitespace change in floater_world_map.xml necessary?

If you want to make changes safely: yes!

2024-10-11 07:49 UTC, LLGuru commented
Using this option could help the reviewer to see the significant differences:
![image](https://github.com/user-attachments/assets/359139a6-7c6c-4924-a639-bf65b27a15f6)

2024-10-11 08:12 UTC, marchcat commented
> Using this option

Well, that was exactly why I'm asking.

2024-10-11 08:27 UTC, Ansariel commented
> Using this option could help the reviewer to see the significant differences: ![image](https://private-user-images.githubusercontent.com/124201357/375670568-359139a6-7c6c-4924-a639-bf65b27a15f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MzU0MDAsIm5iZiI6MTcyODYzNTEwMCwicGF0aCI6Ii8xMjQyMDEzNTcvMzc1NjcwNTY4LTM1OTEzOWE2LTdjNmMtNDkyNC1hNjM5LWJmNjViMjdhMTVmNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMVQwODI1MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMzYwMGI0Mzc2MjgwODgwMzUxNzZiYWIxNTgwZmU3NzlhMDZjY2ZkY2QyZDliZmY4ZTkwOWYyNjQwOTg4NjdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._VFeACGkuWxjM1x0vlofS3pmuQ5hnsWKUJblGo2TUhY)

Still TPVs need to merge these unnecessary changes. But in the end I'm gonna nuke those changes because our worldmap is much better anyway. 😂

2024-10-11 08:32 UTC, marchcat approved these changes
Ok, in this case it's a green light from me 😹

2024-10-11 09:05 UTC, maxim-productengine approved these changes

2024-10-11 10:36 UTC, akleshchev commented
Please clear changes with either Vir or Kyle before merging.

> If you want to make changes safely: yes!

I don't see how that relates to safety, I feel like it's the opposite and makes conflicts likely, especially for TPVs. And it add a huge footprint to history/blame.

2024-10-11 21:05 UTC, kylelinden requested changes
This was implemented incorrectly. Will rewrite /issue/2112 for the desired behaviors, with a request for UX review.

2024-10-11 22:09 UTC, kylelinden commented
> Still TPVs need to merge these unnecessary changes. But in the end I'm gonna nuke those changes because our worldmap is much better anyway. 😂

@Ansariel any chance you could give us a contribution of the FireStorm worldmap?

2024-10-11 22:24 UTC, Ansariel commented
> > Still TPVs need to merge these unnecessary changes. But in the end I'm gonna nuke those changes because our worldmap is much better anyway. 😂
> 
> @Ansariel any chance you could give us a contribution of the FireStorm worldmap?

It's only partially my code, so I don't think I can.

2024-10-14 23:21 UTC, LLGuru commented
Reworked according the new task definition:

1) "Include X,Y coords in the Region/Estate floater, Region tab"
![image](https://github.com/user-attachments/assets/aed32b4d-9fd5-41e9-81e1-4f474345fd77)


2) "When enabled X,Y coords should appear below the region name"
![image](https://github.com/user-attachments/assets/d4fe8d64-c911-459f-857a-7e54060e1e47)

2024-10-15 09:48 UTC, akleshchev approved these changes

2024-10-15 09:48 UTC, akleshchev commented on indra/newview/llworldmapview.cpp
> +                    LLFontGL::getFontSansSerifSmallBold()->renderUTF8(text, 0,
getFontSansSerifSmallBold() is a bit expensive, please consider saving font out of draw().

2024-10-16 13:16 UTC, vir-linden approved these changes
Approved

2024-10-16 16:10 UTC, merged

2024-10-17 22:27 UTC, kylelinden reviewed
Approved.