SL-20361 Avoid of ASSERT (false) in check_rigged_group()
secondlife/viewer pull request #398
Opened 2023-09-28 13:41 UTC by LLGuru

This assert is often being raised on developer's builds when menu "Develop | Render Metadata | Octree" is checked
Usually this happens when animated objects or control avatars get into the field of view, and this leads to process exit

2023-09-28 17:59 UTC, RunitaiLinden requested changes

2023-09-28 17:59 UTC, RunitaiLinden commented on indra/newview/llspatialpartition.cpp
>  				{
don't call check_rigged_group outside of llassert -- it's very slow, so we don't want to call it outside of dev builds

2023-09-28 19:40 UTC, RunitaiLinden approved these changes

2023-09-28 20:17 UTC, merged

2024-03-06 15:57 UTC, AtlasLinden commented
Archived issue: https://github.com/secondlife/jira-archive-internal/issues/70718