Send binary LLSD to LEAP plugins; extend LLSD compatibility, redux
secondlife/viewer pull request #93
Opened 2023-02-25 06:18 UTC by AndrewMeadows

This PR ports work from #29 (which was put in the contribute branch) for the DRTVWR-558 branch (puppetry). It is not clear if the work piling up in contribute will ever be merged, and enhancing the LEAP channel is of particular interest to the puppetry project, so this port is being submitted in case we decide to use it.

Note: with the puppetry project experiencing a long development cycle on its own branch... finally merging it into the main branch will be a messy operation and the work in this PR will contribute to that mess significantly. However, perhaps that will be the best path for the final delivery of this work.

2023-03-01 17:04 UTC, nat-goodspeed requested changes
I'm happy with the set of commits. I do spot a few things that I think should be improved (as commented inline). Are you willing to make those changes? Let me know if you want me to do it instead.

2023-03-01 17:23 UTC, nat-goodspeed commented
Or would it be better for me to make the changes I requested as a PR against `contribute`, and you can cherry-pick those into this branch?

2023-03-01 18:26 UTC, nat-goodspeed commented on indra/llcommon/llkeybind.cpp
> +    for (auto it = mData.begin(); it < end; ++it)
Interesting - a Fawrsk on the `contribute` branch replaced this with a range `for`, eliminating the implicit trimming of empty tail entries. I won't change it back, meaning that if you want to change it on your branch, you'll have to tweak it yourself.

2023-03-01 18:28 UTC, nat-goodspeed commented on indra/llcommon/llsys_objc.mm
> +        patch = int(osVersion.patchVersion);
Already fixed on `contribute` branch

2023-03-02 23:00 UTC, brad-linden commented
recheck

2023-03-03 22:35 UTC, nat-goodspeed commented
@AndrewMeadows, please merge in the changesets from https://github.com/secondlife/viewer/pull/99. Thanks!

2023-03-07 20:29 UTC, nat-goodspeed approved these changes

2023-03-07 20:31 UTC, merged